# Generated by Django 6.0.4 on 2026-04-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='is_missed',
            field=models.BooleanField(default=False),
        ),
    ]
