# Generated by Django 6.0.4 on 2026-04-20 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_studyplan_is_missed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=200)),
                ('total_hours', models.FloatField()),
                ('completed_hours', models.FloatField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.studyplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
