# Generated by Django 6.0.4 on 2026-04-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_studyhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
